//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QuanlimonanNhom16.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_QUAN_LI_MON_AN_NHOM_16_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDD_MFC_DANGNHAP                130
#define IDD_QUAN_LI_MON_AN              132
#define IDD_QUAN_LI_HOA_DON             134
#define IDD_MUAHANG                     136
#define IDD_QL_KHUYENMAI                143
#define IDD_QL_THONG_KE                 145
#define IDD_DIALOG_THANHTOANHD_TT       147
#define IDD_DIALOG1                     149
#define IDB_BITMAP1                     157
#define IDB_BITMAP2                     158
#define IDB_BITMAP3                     159
#define IDB_BITMAP4                     160
#define IDB_BITMAP5                     161
#define IDB_BITMAP6                     162
#define IDB_BITMAP7                     163
#define IDB_BITMAP8                     164
#define IDB_BITMAP9                     165
#define IDD_DOIMK                       166
#define IDB_BITMAP10                    168
#define IDB_BITMAP11                    169
#define IDB_BITMAP12                    170
#define IDB_BITMAP13                    171
#define IDB_BITMAP14                    172
#define IDB_BITMAP15                    173
#define IDB_BITMAP16                    174
#define IDB_BITMAP17                    175
#define IDB_BITMAP18                    176
#define IDB_BITMAP19                    177
#define IDB_BITMAP20                    178
#define IDC_STATIC_Title                1000
#define IDC_BTN_DANGNHAP                1001
#define IDC_BTN_MUANGAY2                1002
#define IDC_BTN_LOGIN                   1002
#define IDC_STATIC_TENDANGNHAP          1003
#define IDC_STATIC_MATKHAU              1004
#define IDC_EDT_USERNAME                1005
#define IDC_EDT_PASSWORD                1006
#define IDC_STATIC_DS_MONAN             1007
#define IDC_LIST_CTRL_DS_MON_AN         1008
#define IDC_BTN_QL_MON_AN               1009
#define IDC_STATIC_TT_MON_AN            1010
#define IDC_STATIC_MA_MON_AN            1011
#define IDC_STATIC_TEN_MON_AN           1012
#define IDC_STATIC_DON_GIA              1013
#define IDC_EDT_MA_MON_AN               1014
#define IDC_EDT_TEN_MON_AN              1015
#define IDC_EDT_DONGIA                  1016
#define IDC_BTN_LAYMA                   1017
#define IDC_BTN_THEM                    1018
#define IDC_BTN_SUA                     1019
#define IDC_BTN_XOA                     1020
#define IDC_STATIC_DS_HOADON            1021
#define IDC_LIST_DS_HOA_DON             1022
#define IDC_LIST_DS_QLHD                1022
#define IDC_STATIC_TT_HOADON            1023
#define IDC_EDT_MA                      1024
#define IDC_EDT_MA_QLHD                 1024
#define IDC_EDT_NGAYLAP                 1025
#define IDC_EDT_NGAYLAP_QLHD            1025
#define IDC_EDT_KH_                     1026
#define IDC_EDT_KH_QLHD                 1026
#define IDC_EDT_DC_                     1027
#define IDC_EDT_DC_QLHD                 1027
#define IDC_EDT_SDT_                    1028
#define IDC_EDT_SDT_QLHD                1028
#define IDC_EDT_TONG_                   1029
#define IDC_EDT_TONG_QLHD               1029
#define IDC_LIST_DS_MON_1_HD            1030
#define IDC_LIST_DS_MON_1_HD_QLHD       1030
#define IDC_STACTIC_MAHOADON_QLHD       1031
#define IDC_STATIC_NL_QLHD              1032
#define IDC_STATIC_KHACHHANG_QLHD       1033
#define IDC_STATIC_DC_QLHD              1034
#define IDC_STATIC_SDT_QLHD             1035
#define IDC_STATIC_TONG_QLHD            1036
#define IDC_LIST_VIEW_DS_MON_AN         1037
#define IDC_STATIC_DS_MONAN_USER        1038
#define IDC_STATIC_TT_HOA_DON_USER      1039
#define IDC_EDT_HOTEN_USER              1040
#define IDC_EDT_DIACHI_USER             1041
#define IDC_EDT_SDT_USER                1042
#define IDC_LIST_CTRL_DS_MONAN_USER     1043
#define IDC_BTN_DATHANG                 1044
#define IDC_STATIC_HOTEN_USER           1045
#define IDC_STATIC_DIACHI_USER          1046
#define IDC_STATIC_SDT_USER             1047
#define IDC_STATIC_DS_MON_AN_USER       1048
#define IDC_BTN_QL_MONAN_               1049
#define IDC_PICTRUE_MUANGAY             1050
#define IDC_STATIC_LOAIMON              1052
#define IDC_COMBO_LOAIMON_              1053
#define IDC_COMBO_LOAI_MON_AN           1054
#define IDC_BTN_TIM_KIEM                1055
#define IDC_STATIC_SOLUONGTON           1056
#define IDC_EDT_SOLUONGCON              1057
#define IDC_STATIC_MA_HOA_DON           1058
#define IDC_STATIC_NGAYLAPHOADON        1059
#define IDC_EDT_MAHOADON                1060
#define IDC_EDIT_NGAYLAP_HOADON         1061
#define IDC_BTN_LAYMAHOADON             1062
#define IDC_STATIC_TONGTHANHTOAN_       1063
#define IDC_EDT_TONGTHANHTOAN_          1064
#define IDC_STATIC_VOUCHER              1065
#define IDC_EDT_MAGIAMGIA               1066
#define IDC_STATIC_VAT_                 1067
#define IDC_EDT_VAT_10                  1068
#define IDC_EDT_MAGIAMGIA_QLHD          1069
#define IDC_STATIC_MAVOUCHER_QLHD       1070
#define IDC_COMBO_LOAI_MON_AN_QLHD      1071
#define IDC_STATIC_THONGTINVOUCHER_QLKM 1073
#define IDC_STATIC_DS_VOUCHER_QLKM      1074
#define IDC_EDT_MAKM_QLKM               1075
#define IDC_EDT_TENKM_QLKM              1076
#define IDC_EDT_HSDKM_QLKM              1077
#define IDC_STATIC_MAVOUCHER_QLKM       1078
#define IDC_STATIC_TENVOUCHER_QLKM      1079
#define IDC_STATIC_HSDVOUCHER_QLKM      1080
#define IDC_LIST_DS_KHUYENMAI_QLKM      1081
#define IDC_STATIC_TRIGIA_QLKM          1082
#define IDC_EDT_GIATRI_QLKM             1083
#define IDC_BTN_THEMKM_QLKM             1084
#define IDC_BTN_CAPNHATKM_QLKM          1085
#define IDC_BTN_XOAKM_QLKM              1086
#define IDC_BTN_QLMONAN_QLKM            1087
#define IDC_BTN_QLHD_QLKM               1088
#define IDC_BTN_QL_KHUYENMAI_QLHD       1089
#define IDC_BTN_QLKM_QLMONAN            1089
#define IDC_BTN_LAYMA_QLKM              1090
#define IDC_LIST_DS_HOADON_THONGKE      1091
#define IDC_STATIC_DS_HOA_DON_TK        1092
#define IDC_LIST_DS_HOADON_TIMKIEM_THONGKE 1093
#define IDC_EDT_MA_THONGKE              1094
#define IDC_STATIC_THONGKEHOADONTHEOTIMMKIEM_THONGKE 1095
#define IDC_BTN_QUANLIMONAN_THONGKE     1096
#define IDC_BTN_QLHOADON_THONGKE        1097
#define IDC_BTN_QLKM_THONGKE            1098
#define IDC_STATIC_NGAYTHANGNAM_TU_NGAY_THONGKE 1100
#define IDC_STATIC_TUNGAY_THONGKE       1101
#define IDC_COMBO_TUNGAY_NGAY_THONGKE   1103
#define IDC_COMBO_TUNGAY_THANG_TK       1105
#define IDC_COMBO_TUNGAY_NAM_TK         1106
#define IDC_STATIC_DENNGAY_TK           1107
#define IDC_STATIC_DENNGAY_NGAYTHANGNAM_TK 1109
#define IDC_COMBO_DENNGAY_NGAY_TK       1111
#define IDC_COMBO_DENNGAY_THANG_TK      1112
#define IDC_COMBO_DENNGAY_NAM_TK        1113
#define IDC_EDIT_TENKH_TK               1116
#define IDC_EDT_SDT_TK                  1118
#define IDC_EDT_GIATRI_TK               1120
#define IDC_BTN_TIMKIEM_TK              1121
#define IDC_BTN_QLTK_HD                 1122
#define IDC_BTN_QLTK_KM                 1123
#define IDC_BTN_QLTHONGKE_MONAN         1123
#define IDC_BTN_TIMKIEM_THEONGAY        1124
#define IDC_BTN_TIMKIEM_THEOTEN_TK      1125
#define IDC_BTN_TIMTHEOSDT_TK           1126
#define IDC_BTN_TIMKIEM_GIATRI_TK       1127
#define IDC_STATIC_GROUP_TENKH_TK       1128
#define IDC_STATIC_GROUP_MA_TK          1129
#define IDC_STATIC_GROUP_NGAYTHANGNAM_TK 1130
#define IDC_STATIC_GROUP_SDT_TK         1131
#define IDC_STATIC_GROUP_GIATRI_TK      1132
#define IDC_PICTURE_DANGNHAP_DN         1133
#define IDC_COMBO_TIMTHEOMA_TK          1134
#define IDC_COMBO_TIMTHEOTHOIGIAN_TK    1135
#define IDC_COMBO_TIMTHEOSDT_TK         1136
#define IDC_BTN_SAPXEPTHEOMA_TK         1137
#define IDC_BTN_SXTHEOSDT_TK            1138
#define IDC_COMBO_SXTHEOGIATRI_TK       1139
#define IDC_BUTTON_SXTHEOGIATRI_TK      1140
#define IDC_COMBO_SXTHEOTENKH_TK        1141
#define IDC_BUTTON_SXTHEOTENKH_TK       1142
#define IDC_STATIC_TINHTONGHD_TK        1143
#define IDC_EDT_TINHTONGHD_TK           1144
#define IDC_STATIC_GROUP_KHACHHANGMUA_MH 1145
#define IDC_COMBO_SX_MONAN_MH           1146
#define IDC_BTN_HIENTHI_DS_MONAN_MH     1147
#define IDC_STATIC_THONGTINHD_TT        1148
#define IDC_STATIC_MAHD_TT              1149
#define IDC_STATIC_NGAYLAPHD_TT         1150
#define IDC_STATIC_KH_TT                1151
#define IDC_STATIC_DIACHI_TT            1152
#define IDC_STATIC_SDT_TT               1153
#define IDC_STATIC_MAGIAMGIA_TT         1154
#define IDC_EDIT_SHD_TT                 1155
#define IDC_EDIT_NGAYLAP_TT             1156
#define IDC_EDIT_HOTEN_TT               1157
#define IDC_EDIT_DIACHI_TT              1158
#define IDC_EDIT_SDT_TT                 1159
#define IDC_EDIT_MAGIAMGIA_TT           1160
#define IDC_RADIO_TTSKNH_TT             1161
#define IDC_STATIC_THANHTOAN_TT         1162
#define IDC_STATIC_TONGIATRI_TT         1163
#define IDC_EDIT_TONGGIATRI_TT          1164
#define IDC_RADIO_TTSKNH_TT2            1165
#define IDC_STATIC_GROUP_TTQUATHE_TT    1166
#define IDC_STATIC_SOTHE_TT             1167
#define IDC_EDIT_SOTHE_TT               1168
#define IDC_STATIC_TENINTTHE_TT         1169
#define IDC_EDIT_TENTRENTHE_TT          1170
#define IDC_STATIC_NGAYHETHAN           1171
#define IDC_EDIT_NGAYHETHAN_TT          1172
#define IDC_STATIC_MACVV_TT             1173
#define IDC_EDIT_MACVV_TT               1174
#define IDC_BUTTON_XACDINH_TT           1175
#define IDC_BUTTON_HUY_TT               1176
#define IDC_BTN_XOAHD_QLHD              1177
#define IDC_BTN_CHINHSUAHD_QLHD         1178
#define IDC_LIST_DS_MONAN_TKMA          1182
#define IDC_LIST_DS_MONANTHONGKE_TKMA   1183
#define IDC_STATIC_DSMONAN_TKMA         1184
#define IDC_STATIC_DS_THONGKEMONAN_TKMA 1185
#define IDC_BTN_QLMONAN_TKMA            1186
#define IDC_BTN_QLHOADON_TKMA           1187
#define IDC_BTN_QLKM_TKMA               1188
#define IDC_BTN_TKHD_TKMA               1189
#define IDC_BTN_THONGKEMONAN_QLKM       1190
#define IDC_BTN_THONGKEMONAN_TKMA       1191
#define IDC_BTN_THONGKEMONAN_QLHD       1192
#define IDC_BTN_THONGKEMONAN_QLMA       1193
#define IDC_STATIC_TTKH                 1194
#define IDC_BMP_LOGO                    1195
#define IDC_CBB_LOAIMON_TKMA            1196
#define IDC_STATIC_NGAYTHANGNAM_TKMA    1197
#define IDC_STATIC_TUNGAY_TKMA          1198
#define IDC_STATIC_DENNGAY_TKMA         1199
#define IDC_COMBO_TUNGAY_NGAY_TKMA      1200
#define IDC_COMBO_TUNGAY_THANG_TKMA     1201
#define IDC_COMBO_TUNGAY_NAM_TKMA       1202
#define IDC_COMBO_SXTANGGIAM_TKMA       1203
#define IDC_COMBO_DENNGAY_NGAY_TKMA     1204
#define IDC_COMBO_DENNGAY_THANG_TKMA    1205
#define IDC_COMBO_DENNGAY_NAM_TKMA      1206
#define IDC_BTN_TIMKIEM_TKMA            1207
#define IDC_STATIC_GROUP_NGAYTHANGNAM_TKMA 1208
#define IDC_STATIC_TIMTHEODONGIA_TKMA   1209
#define IDC_EDIT_DONGIA_TKMA            1211
#define IDC_COMBO_DONGIA_TKMA           1212
#define IDC_BUTTON_TIMKIEMTHEODONGIA_TKMA 1213
#define IDC_BUTTON_SXTHEODONGIA_TKMA    1214
#define IDC_STATIC_GOURPLOAI_TKMA       1215
#define IDC_BUTTON_LOAIMON_TKMA         1216
#define IDC_COMBO_LOAIMON_TKMA          1217
#define IDC_BUTTON_DOIMATKHAU           1218
#define IDC_STATIC_USERNAME_DMK         1219
#define IDC_EDIT_USERNAME_DMK           1220
#define IDC_MATKHAUCU_DMK               1221
#define IDC_EDIT_MATKHACU_DMK           1222
#define IDC_MATKHAUMOI_DMK              1223
#define IDC_EDIT_MATKHACU_DMK2          1224
#define IDC_MATKHAUMOI2_DMK             1225
#define IDC_EDIT_MATKHACU_DMK3          1226
#define IDC_STATIC_T_DOIMK              1227
#define IDC_BUTTON_XACNHAN_DMK          1228
#define IDC_BUTTON_HUY_DMK              1229
#define IDC_STATIC_LOAIMON_TKMA         1231
#define IDC_GROUP_THONGTINQLMA          1232
#define IDC_STATIC_TKTM                 1233
#define IDC_STATIC_TKTG                 1234
#define IDC_STATIC_TKTKH                1236
#define IDC_STATIC_TKSDT                1238
#define IDC_STATIC_TKSDT2               1240
#define IDC_STATIC_TKGTDH               1240

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1234
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
